### ISSUE TITLE
Can I flash the respeaker firmware to LinkIt7688

### ISSUE THREAD

**Issue by juncaofish** [respeaker/respeaker-feed#1]
Hi, I make a firmware based on https://github.com/respeaker/openwrt and respeaker/respeaker-feed. The final bin has the size of 4.8MB, comparing to the LinkIt7688's 21MB. Can I flash the respeaker one to LinkIt board, just to verify the respeaker environment is successfully compiled?

**Comment by StephaneRenouard** [comment]
You can, but lot of things are missing in comparaison to the stock bin. You should add missing stuffs when make menuconfig.

**Comment by juncaofish** [comment]
I tried to pip install pyaudio on LinkIt, but got a result like: unable to execute 'mipsel-openwrt-linux-uclibc-gcc' . I noticed a makefile here:https://github.com/respeaker/respeaker-feed/tree/master/python-pyaudio . How can I take a check in the respeaker firmware for the pyaudio package being made successfully?

**Comment by StephaneRenouard** [comment]
mipsel-openwrt-linux-uclibc-gcc is the cross compiler executable GCC that you got fro either SDK or crosscompil package (see Mediatek website to get one). This executable is missing on a running linkit or speaker as you have to cross compile C/C++ on an other system. 

I encountered lot of issues with pyaudio and pip with linkit. I only solved these by cross compiling custom images or packages. Especialy this one. 

The stock image for respeaker embedded this package directly.

**Comment by juncaofish** [comment]
hmm, thanks a lot! LinkIt has no WM8960 for audio features, so do you know any workaround to use pyaudio on LinkIt?

**Comment by StephaneRenouard** [comment]
yes. First of all, you can use the breadboard from seeed that includes all you need for audio (kmd-sound-*). Remember that the DUO version is using I2S pins for arduino, meaning that the V1 breadboard cannot uses audio with DUO. Prefer to use linkit 7688 (not duo) with V1 breadboard. Cheek on seeed website for this board. I actually did not receveid V2 that should arrive soonly. 

But, I prefer to use an external sound car, such as the one one USB from cmedia. I picked a Ugreen on amazon for less than 5$. The needed package is kmod-sound-usb, available on opkg. 

The external sound card can be used directly on the USB breadboard, or you can remove the usb plug and cable directly on the linkit (USB+/-/data).

**Comment by StephaneRenouard** [comment]
breadboard from seeed: 
https://www.seeedstudio.com/Breakout-for-LinkIt-Smart-7688-p-2590.html

**Comment by juncaofish** [comment]
Big thanks for the perfect answer.

**Comment by juncaofish** [comment]
Hello, I flash the firmware made with the latest config.respeaker file to LinkIt7688. The behavior is a little different with LinkIt original firmware:
1. The wifi led lights on forever.  
2. can connect to the AP: Respeakerxxxxx, but can't open 192.168.100.1 in web browser.
3. can  ssh to root@192.168.100.1 , but the password is not "root" . 

Is this still in development? How could I check if the build firmware is ok?

**Comment by xiongyihui** [comment]
Use `telnet 192.168.100.1`  if the root user's password is not set

**Comment by juncaofish** [comment]
Ok, I gave a try with your built[ firmware](https://s3-us-west-2.amazonaws.com/respeaker.io/firmware/ramips-openwrt-latest-LinkIt7688-squashfs-sysupgrade.bin) , but still failed in opening 192.168.100.1 in web browser. However, ssh works with root user. 
So is the juci web interface still in dev? Thanks.

**Comment by xiongyihui** [comment]
Are you using the respeaker branch of https://github.com/respeaker/openwrt? At the branch, root's password is `root`, and you will see the prompt:
```
BusyBox v1.23.2 (2016-10-19 21:04:59 PDT) built-in shell (ash)

           _       __                       
          |_)  _  (_  ._   _   _. |   _  ._ 
          | \ (/_ __) |_) (/_ (_| |< (/_ |  
                      |                    
 -----------------------------------------------------
 CHAOS CALMER (Chaos Calmer, v0.9.99)
 -----------------------------------------------------
  * 1 1/2 oz Gin            Shake with a glassful
  * 1/4 oz Triple Sec      of broken ice and pour
  * 3/4 oz Lime Juice       unstrained into a goblet.
  * 1 1/2 oz Orange Juce
  * 1 tsp. Grenadine Syrup
 -----------------------------------------------------
 issue: http//www.seeed.cc/respeaker
 -----------------------------------------------------
 default: username:root password:root
 ----------------------------------------------------- 
root@ReSpeaker:/# 
```

**Comment by juncaofish** [comment]
yes. I copy config.respeaker to .config and then make the firmware directly. Is that correct ?

**Comment by xiongyihui** [comment]
If the `respeaker` branch is used, root's password should be `root`. It's not related with config.respeaker. `config.respeaker` is kind of out date. You'd better `make menuconfig` to select the packages you want, or just using the buillt firmware.

**Comment by juncaofish** [comment]
Another question for audio, I didn't get a Seeed USB breadboard in hand.
But I have a mini [USB microphone](https://item.taobao.com/item.htm?spm=a1z09.2.0.0.u1XLMN&id=530831829755&_u=d7mkrm15703), could I connect it to LinkIt via a USB OTG cable? Or should I remove the usb plug and cable directly on the linkit (USB+/-/data).

**Comment by xiongyihui** [comment]
I think both should work if the usb microphone is standard usb audio class device.

**Comment by juncaofish** [comment]
Thanks a lot. 
Some error log after make menuconfig for my customized modules..
!!! yui-compressor is missing. Please install package yui-compressor or yuicompressor.
!!! lessc (less css compiler) is missing on your system. Please install it!
JUCI build dependencies are missing!.

What kind of dependency should I install for JUCI?

**Comment by juncaofish** [comment]
I manage to make it with the following 2 commands:
```
sudo apt-get install yui-compressor
sudo npm install -g  less
```
Really not easy for a complete make process due to the bad network condition.

**Comment by juncaofish** [comment]
Still , fail when log in as root user, password with root.

➜  mbp telnet 192.168.100.1
Trying 192.168.100.1...
telnet: connect to address 192.168.100.1: Connection refused
telnet: Unable to connect to remote host
➜  mbp ssh root@192.168.100.1
Password:
Password:
Password:
Permission denied (publickey,keyboard-interactive).

 Is there any magic configuration for root user/passwd during compile the firmware except the .config file (attached my config)?  Thanks for your time.


[config.txt](https://github.com/respeaker/respeaker-feed/files/648833/config.txt)

Could you share the difference for your .config?

**Comment by juncaofish** [comment]
```
Type "help", "copyright", "credits" or "license" for more information.
 >>> import pyaudio
 >>> pyaudio.PyAudio()
```
Expression 'ioctl( devHandle, SNDCTL_DSP_SPEED, &sr )' failed in 'src/hostapi/oss/pa_unix_oss.c', line: 421
Expression 'ioctl( devHandle, SNDCTL_DSP_SPEED, &sr )' failed in 'src/hostapi/oss/pa_unix_oss.c', line: 421

How does this error happen?

**Comment by juncaofish** [comment]
Hey,  I got stuck in the dev environment issue:
```
root@ReSpeaker:~# python
Python 2.7.12 (default, Dec 26 2016, 15:21:55)
[GCC 4.8.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mraa
>>> mraa.Spi(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/mraa.py", line 1304, in __init__
    this = _mraa.new_Spi(bus)
ValueError: Error initialising SPI bus
>>> mraa.Gpio(10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/mraa.py", line 820, in __init__
    this = _mraa.new_Gpio(pin, owner, raw)
ValueError: Invalid GPIO pin specified
>>> exit()
root@ReSpeaker:~# python
Python 2.7.12 (default, Dec 26 2016, 15:21:55)
[GCC 4.8.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyaudio
>>> pa = pyaudio.PyAudio()
This step will cause the board reboot ..
```
I know you're very busy, but if you can figure out some possible reason I'll really appreciate.

I've purchased the Breakout for LinkIt Smart 7688 v2.0, though I don't think it's related with the LinkIt board , because your firmware doesn't have the two issues above. 

Addition, the audio driver should be well installed. Test script:

```
root@ReSpeaker:~# arecord -D plughw:1 --duration=3 -f S16_LE -r 16000 rectest.wav
Recording WAVE 'rectest.wav' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
root@ReSpeaker:~# ls
Tchaikovsky_Concerto_No.1p.mp3  rectest.wav                     sd_daemon.sh
autorun.sh                      sd1
root@ReSpeaker:~# arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: I2S [MTK APSoC I2S], device 0: WMserious PCM wm8960-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: Device [USB Audio Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
root@ReSpeaker:~#
```

**Comment by xiongyihui** [comment]
It seems not all GPIOs are exported to MRAA.  You can try SysFS GPIO

```
echo 10 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio10/direction
echo 1 > /sys/class/gpio/gpio10/value
```

If you get `Expression 'ioctl( devHandle, SNDCTL_DSP_SPEED, &sr )' failed in 'src/hostapi/oss/pa_unix_oss.c'` from pyaudio, you should remove oss audio when compiling, we use alsa audio instead.

No idea why your build doesn't work.

The sources we use are all there:  https://github.com/respeaker/openwrt, https://github.com/respeaker/package respeaker branch and https://github.com/respeaker/respeaker-feed

**Comment by juncaofish** [comment]
The respeaker-feed is defined in feeds.conf.default for respeaker/openwrt repo .  
So should the feeds.conf.default (in respeaker/openwrt repo) add a line  "src-git packages https://github.com/respeaker/packages.git" at the end? 

 I noticed some changes for respeaker/packages that I may never include when compiling(　ﾟ皿ﾟ) That may be the root cause for the strange issues I have met (like login/pyaudio/mraa issues).

**Comment by amythical** [comment]
Could you flash respeaker to LinkIt7688?
I am having issues with sound - it doesnt play.
